In [1]:
import numpy as np
from numpy.typing import NDArray
# from solvers import (
#     select_by_margin_from_joint_limit,
#     _find_kth_true,
#     select_by_minimum_joint_motion,
# )

%load_ext autoreload
%autoreload 2

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.where(x >5)
a

(array([6, 7, 8, 9]),)

In [9]:
# Test 1: Test solution is minimizer of max joint motion.
q_curr = np.array([720, 160, 30])
q_sols = np.array(
    [
        [1, 140 + 360, 90],  # max joint motion = 60
        [-720, 120, 50 + 360],  # max joint motion = 40
    ]
)
q_sols = np.deg2rad(q_sols)
q_curr = np.deg2rad(q_curr)

expected_sol_idx = 1
q_best_idx = select_by_minimum_joint_motion(q_sols, q_curr)
assert q_best_idx == expected_sol_idx


# Test 2:  Test MAE tie breaker
q_curr = np.array([0, 30, 20])
q_sols = np.array(
    [
        [10, 40, 80],  # max joint motion = 60, mae = (10+10+60)/3
        [10 + 360, 10, 80 + 360],  # max joint motion = 60, mae = (10+20+60)/3
    ]
)
q_sols = np.deg2rad(q_sols)
q_curr = np.deg2rad(q_curr)
expected_sol_idx = 0
q_best_idx = select_by_minimum_joint_motion(q_sols, q_curr)
assert q_best_idx == expected_sol_idx


# Test 3:  Same solutions.
q_curr = np.array([0, 30, 20])
q_sols = np.array(
    [
        [10, 40, 80],
        [10, 40, 80],
    ]
)
q_sols = np.deg2rad(q_sols)
q_curr = np.deg2rad(q_curr)
expected_sol_idx = 0  # argmin just finds the first min.
q_best_idx = select_by_minimum_joint_motion(q_sols, q_curr)
assert q_best_idx == expected_sol_idx

In [10]:
bool_arr = np.array([True, False, False, True, False, False, True])
true_idx = [0, 3, 6]
k = [1, 2, 3]
for i in range(len(k)):
    assert _find_kth_true(bool_arr, k[i]) == true_idx[i]

In [11]:
q_limits = np.array(
    [
        [-60, 30, 0],
        [60, 90, 100],
    ]
)
q_limits = np.deg2rad(q_limits)

# Test 1: Choose by max margin
q_sols = np.array(
    [
        [-50, 70, 50],  # margin = 10 deg
        [0, 70, 50],  # margin = 20 deg
    ]
)
q_sols = np.deg2rad(q_sols)

expected_sol_idx = 1
q_best_idx = select_by_margin_from_joint_limit(q_sols, q_limits)
assert expected_sol_idx == q_best_idx


# Test 2: multiple same max margin, break tie with mean margin
q_sols = np.array(
    [
        [-50, 70, 50],  # margin = 10 deg
        [0, 70, 40],  # margin = 20 deg, mean margin = (60+20+40)/3
        [0, 70, 50],  # margin = 20 deg, mean margin = (60+20+50)/3
    ]
)
q_sols = np.deg2rad(q_sols)
expected_sol_idx = 2
q_best_idx = select_by_margin_from_joint_limit(q_sols, q_limits)
assert expected_sol_idx == q_best_idx

[0.17453293 0.34906585]
0.34906585039886595
[False  True]
[0.17453293 0.34906585 0.34906585]
0.34906585039886595
[False  True  True]
[0.46542113 0.6981317  0.75630934]
